const Discord = require("discord.js");
const client = new Discord.Client();//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
const ayarlar = require("./ayarlar.json");
const chalk = require("chalk");
const moment = require("moment");
var Jimp = require("jimp");
const { Client, Util } = require("discord.js");
const weather = require("weather-js");
const fs = require("fs");//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
const db = require("quick.db");
const http = require("http");
const express = require("express");//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
require("./util/eventLoader")(client);
const path = require("path");
const request = require("request");
const snekfetch = require("snekfetch");//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
const queue = new Map();
const YouTube = require("simple-youtube-api");
const ytdl = require("ytdl-core");
//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
const app = express();
app.get("/", (request, response) => {
  console.log(Date.now() + " BOT AKTIF");
  response.sendStatus(200);
});
app.listen(process.env.PORT);
setInterval(() => {
  http.get(`http://${process.env.PROJECT_DOMAIN}.glitch.me/`);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
}, 280000);

var prefix = ayarlar.prefix;
//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
const log = message => {
  console.log(`${message}`);
};

client.commands = new Discord.Collection();
client.aliases = new Discord.Collection();//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
fs.readdir("./komutlar/", (err, files) => {
  if (err) console.error(err);
  log(`${files.length} Komut Var!`);
  files.forEach(f => {
    let props = require(`./komutlar/${f}`);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
    log(`${props.help.name} Yüklendii`);
    client.commands.set(props.help.name, props);
    props.conf.aliases.forEach(alias => {
      client.aliases.set(alias, props.help.name);
    });
  });//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
});

client.reload = command => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  return new Promise((resolve, reject) => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
    try {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      delete require.cache[require.resolve(`./komutlar/${command}`)];//lordcreative- discord.gg/codeworld
      let cmd = require(`./komutlar/${command}`);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      client.commands.delete(command);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      client.aliases.forEach((cmd, alias) => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
        if (cmd === command) client.aliases.delete(alias);
      });
      client.commands.set(command, cmd);
      cmd.conf.aliases.forEach(alias => {
        client.aliases.set(alias, cmd.help.name);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      });//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      resolve();//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
    } catch (e) {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      reject(e);
    }//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  });//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
};//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld

client.load = command => {
  return new Promise((resolve, reject) => {
    try {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      let cmd = require(`./komutlar/${command}`);
      client.commands.set(command, cmd);
      cmd.conf.aliases.forEach(alias => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
        client.aliases.set(alias, cmd.help.name);
      });
      resolve();
    } catch (e) {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      reject(e);
    }
  });//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
};

client.unload = command => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  return new Promise((resolve, reject) => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
    try {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg///lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworldcodeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      delete require.cache[require.resolve(`./komutlar/${command}`)];//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      let cmd = require(`./komutlar/${command}`);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      client.commands.delete(command);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      client.aliases.forEach((cmd, alias) => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
        if (cmd === command) client.aliases.delete(alias);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      });//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      resolve();//lordcreative- discord.gg/codeworld//lor//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworlddcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
    } catch (e) {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
      reject(e);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
    }
  });
};

client.elevation = message => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  if (!message.guild) {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
    return;
  }
  let permlvl = 0;
  if (message.member.hasPermission("BAN_MEMBERS")) permlvl = 2;//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  if (message.member.hasPermission("ADMINISTRATOR")) permlvl = 3;//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  if (message.author.id === ayarlar.sahip) permlvl = 4;//lordcreative- discord.//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworldgg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  return permlvl;
};

var regToken = /[\w\d]{24}\.[\w\d]{6}\.[\w\d-_]{27}/g;//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
// client.on('debug', e => {
//   console.log(chalk.bgBlue.green(e.replace(regToken, 'that was redacted')));//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
// });

client.on("warn", e => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  console.log(chalk.bgYellow(e.replace(regToken, "that was redacted")));//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
});

client.on("error", e => {//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
  console.log(chalk.bgRed(e.replace(regToken, "that was redacted")));//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld
});//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld

client.login(ayarlar.token);//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld//lordcreative- discord.gg/codeworld

